### ISSUE TITLE
Use `user` defined in Dockerfile or defined in docker-compose.yml

### ISSUE THREAD

**Issue by nvick** [MicrosoftDocs/vsonline#488]
While bringing up a docker-compose based Rails app we ran into the following issue with the user defined in our Dockerfile and docker-compose.yml.

In our Dockerfile and docker-compose.yml, we have a ruby user defined in both files to be the user in the service, but it was being ignored. We did not add `containerUser` to our `.devcontainer.json` initially based on the current documentation.

| `containerUser` | string or array | The user that will be used when creating the container. If the property is undefined, it defaults to either root or the last USER instruction in the Dockerfile. |

Once we added it the environment would come up as the ruby user.

**Comment by edgonmsft** [comment]
Hi Nate!

Thanks for pointing this out, would you be able to share part of your docker file and/or docker-compose file so that we can diagnose the issue?

Thanks!

**Comment by nvick** [comment]
Sure thing!

Dockerfile
```
ARG RUBY_VERSION=2.6
FROM ruby:$RUBY_VERSION

ENV SHELL=/bin/bash

ARG DEBIAN_FRONTEND=noninteractive

ARG NODE_VERSION=11
RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -yq && apt-get install -yq \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common \
  build-essential \
  nodejs \
  yarn \
  locales \
  git \
  netcat \
  vim \
  sudo

# Install Docker (Yes, in docker)
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
  add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian \
    $(lsb_release -cs) \
    stable"

RUN apt-get update && apt-get install -yq \
  docker-ce \
  docker-ce-cli \
  containerd.io

RUN groupmod -g 800 docker

# Install Compose

RUN curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
  chmod +x /usr/local/bin/docker-compose

ARG UID
ENV UID $UID
ARG GID
ENV GID $GID
ARG USER=ruby
ENV USER $USER

RUN groupadd -g $GID $USER && \
    useradd -u $UID -g $USER -m -s /bin/bash $USER && \
    usermod -p "*" $USER && \
    usermod -aG sudo $USER && \
    usermod -aG docker $USER && \
    echo "$USER ALL=NOPASSWD: ALL" >> /etc/sudoers.d/50-$USER

ENV LANG C.UTF-8

ENV BUNDLE_PATH /gems
ENV BUNDLE_HOME /gems

ARG BUNDLE_JOBS=20
ENV BUNDLE_JOBS $BUNDLE_JOBS

ARG BUNDLE_RETRY=5
ENV BUNDLE_RETRY $BUNDLE_RETRY

ENV GEM_HOME /gems
ENV GEM_PATH /gems

ENV PATH /gems/bin:$PATH

ARG INSTALL_PG_CLIENT=false
RUN if [ "$INSTALL_PG_CLIENT" = true ]; then \
    apt-get install -y postgresql-client \
;fi

RUN mkdir -p "$GEM_HOME" && chown $USER:$USER "$GEM_HOME"
RUN mkdir -p /app && chown $USER:$USER /app

WORKDIR /app

RUN mkdir -p node_modules && chown $USER:$USER node_modules
RUN mkdir -p public/packs && chown $USER:$USER public/packs
RUN mkdir -p tmp/cache && chown $USER:$USER tmp/cache
RUN mkdir -p /home/ruby/.vsonline && chown $USER:$USER /home/ruby/.vsonline

ENV DEBIAN_FRONTEND=dialog

USER $USER

RUN gem install bundler

USER $USER
```
docker-compose.yml
```
version: '3.0'

services:
  rails:
    build:
      context: ./docker/ruby
      args:
        - RUBY_VERSION=2.6.5
        - BUNDLE_JOBS=15
        - BUNDLE_RETRY=2
        - NODE_VERSION=10
        - INSTALL_PG_CLIENT=true
        - UID=1000
        - GID=1000
    environment:
      - DATABASE_USER=postgres
      - DATABASE_HOST=postgres
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    entrypoint: ./docker/ruby/entrypoint.sh
    volumes:
      - .:/app:cached
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    ports: 
      - "3000:3000"
    user: ruby
    tty: true
    stdin_open: true
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gems:
  postgres:
  node_modules:
  packs:
  rails_cache:
```
